"""lock/requirements.txt: hash-pinned, universal, the source of truth for
versions; it follows the install, never lowers anything, and requirements.txt
never runs ahead of it.

2026-09-22: the first real OSV scan showed why 17 direct pins were not
enough (anyio 4.13.0 inside two advisories). 2026-09-23 (owner: "erstmal A"):
the lock became a uv-compiled universal file with markers and sha256 hashes,
CI installs it with --require-hashes, the launchers raise through the same
hash check. Plain `name==version` lines (the pre-uv lock) still work.

    python tests/test_deps_lock.py
"""
import pathlib
import sys
import tempfile
from types import SimpleNamespace

_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT))

from src import deps_lock as dl  # noqa: E402

UV_TEXT = """# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.txt --universal --generate-hashes -o lock/requirements.txt
anyio==4.14.2 \\
    --hash=sha256:aaaa \\
    --hash=sha256:bbbb
    # via
    #   httpx
    #   starlette
pywin32==311 ; sys_platform == 'nonexistent' \\
    --hash=sha256:cccc
    # via pystray
starlette==1.3.1 \\
    --hash=sha256:dddd
    # via fastapi
plainpkg==1.0
"""

REQ = """# Curatarr — Requirements
fastapi==0.141.1
uvicorn[standard]==0.53.0   # extras are not part of the name
PyJWT==2.14.0
"""


def test_parse_keeps_versions_markers_hashes_and_via_comments():
    e = dl.parse_lock(UV_TEXT)
    assert set(e) == {"anyio", "pywin32", "starlette", "plainpkg"}
    assert e["anyio"].version == "4.14.2" and e["anyio"].hashes == ["sha256:aaaa", "sha256:bbbb"]
    assert e["anyio"].comments == ["    # via", "    #   httpx", "    #   starlette"]
    assert e["pywin32"].marker == "sys_platform == 'nonexistent'" and e["pywin32"].hashes == ["sha256:cccc"]
    assert e["plainpkg"].hashes == [] and e["plainpkg"].marker is None
    again = dl.parse_lock(dl.format_lock(e, dl.lock_header(UV_TEXT)))
    assert {k: (v.version, v.marker, v.hashes) for k, v in again.items()} == \
        {k: (v.version, v.marker, v.hashes) for k, v in e.items()}, "format → parse is a fixed point"
    assert dl.lock_header(UV_TEXT).startswith("# This file was autogenerated by uv")
    assert dl.parse_lock("")== {}


def test_direct_pins_keep_extras_apart_from_the_name():
    pins = dl.direct_pins(REQ)
    assert pins == {"fastapi": ("0.141.1", []), "uvicorn": ("0.53.0", ["standard"]), "pyjwt": ("2.14.0", [])}


def test_compare_names_below_above_unlocked_unused_and_foreign():
    installed = {"anyio": "4.13.0", "starlette": "1.4.0", "plainpkg": "1.0", "sniffio": "1.3.1"}
    rep = dl.compare(UV_TEXT, installed)
    assert rep.below == [("anyio", "4.13.0", "4.14.2")]
    assert rep.above == [("starlette", "1.4.0", "1.3.1")]
    assert rep.unlocked == ["sniffio"]
    assert rep.foreign == ["pywin32"] and rep.unused == [], "a marker that rules the entry out here is not 'unused'"
    assert rep.hashed is False, "one plain line means the file is not fully hashed"
    assert not rep.clean
    hashed_only = "\n".join(l for l in UV_TEXT.splitlines() if not l.startswith("plainpkg")) + "\n"
    assert dl.compare(hashed_only, {"anyio": "4.14.2", "starlette": "1.3.1"}).hashed is True


def test_raise_below_goes_through_a_temporary_hashed_file():
    calls = []

    def fake_run(cmd, **kw):
        path = cmd[cmd.index("-r") + 1]
        calls.append((list(cmd), pathlib.Path(path).read_text(encoding="utf-8")))
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    rep = dl.compare("\n".join(l for l in UV_TEXT.splitlines() if not l.startswith("plainpkg")) + "\n",
                     {"anyio": "4.13.0", "starlette": "1.3.1"})
    assert dl.raise_below(rep, run=fake_run, log=lambda s: None) == []
    cmd, body = calls[0]
    assert cmd[:4] == [sys.executable, "-m", "pip", "install"] and "--require-hashes" in cmd and "--no-deps" in cmd
    assert body.startswith("anyio==4.14.2 \\") and "--hash=sha256:aaaa" in body and "starlette" not in body
    assert not pathlib.Path(cmd[cmd.index("-r") + 1]).exists(), "the temporary file is removed"

    # plain lock: no hash check, and a failing batch falls back to one call per package
    attempts = []

    def failing_then_ok(cmd, **kw):
        body = pathlib.Path(cmd[cmd.index("-r") + 1]).read_text(encoding="utf-8")
        attempts.append(body.count("=="))
        ok = attempts[-1] == 1 and body.startswith("b==")
        return SimpleNamespace(returncode=0 if ok else 1, stdout="", stderr="boom")

    rep2 = dl.compare("a==2.0\nb==2.0\n", {"a": "1.0", "b": "1.0"})
    assert dl.raise_below(rep2, run=failing_then_ok, log=lambda s: None) == ["a"]
    assert attempts == [2, 1, 1], "one batch, then one call per package"


def test_pypi_hashes_and_merged_follow_the_install_with_fresh_hashes():
    def fetch(url):
        assert url.endswith("/starlette/1.4.0/json") or url.endswith("/sniffio/1.3.1/json")
        return {"urls": [{"digests": {"sha256": "ffff"}}, {"digests": {"sha256": "eeee"}, "yanked": True},
                         {"digests": {"sha256": "ffff"}}]}

    assert dl.pypi_hashes("starlette", "1.4.0", fetch) == ["sha256:ffff"], "yanked skipped, duplicates folded"
    assert dl.pypi_hashes("x", "1", lambda url: (_ for _ in ()).throw(OSError("offline"))) == []

    text = "\n".join(l for l in UV_TEXT.splitlines() if not l.startswith("plainpkg")) + "\n"
    rep = dl.compare(text, {"anyio": "4.13.0", "starlette": "1.4.0", "sniffio": "1.3.1"})
    out = dl.merged(rep, {"sniffio": "sniffio"}, fetch, log=lambda s: None)
    assert out["anyio"].version == "4.14.2", "below: the lock line stays, the raise is retried"
    assert out["starlette"].version == "1.4.0" and out["starlette"].hashes == ["sha256:ffff"]
    assert out["starlette"].comments == ["    # via fastapi"], "the provenance comment survives"
    assert out["sniffio"].version == "1.3.1" and out["sniffio"].hashes == ["sha256:ffff"]
    offline = dl.merged(rep, {"sniffio": "sniffio"}, lambda url: (_ for _ in ()).throw(OSError()), log=lambda s: None)
    assert offline["starlette"].version == "1.3.1" and "sniffio" not in offline, "offline: nothing invented"


def test_sync_pins_repeats_the_lock_in_requirements_and_keeps_the_line_shape():
    with tempfile.TemporaryDirectory() as d:
        req = pathlib.Path(d) / "requirements.txt"
        lock = pathlib.Path(d) / "lock" / "requirements.txt"
        lock.parent.mkdir()
        req.write_text(REQ, encoding="utf-8")
        lock.write_text("fastapi==0.142.0\nuvicorn==0.54.0\nPyJWT==2.14.0\n", encoding="utf-8")
        assert dl.sync_pins(req, lock) == 2
        text = req.read_text(encoding="utf-8")
        assert "fastapi==0.142.0\n" in text
        assert "uvicorn[standard]==0.54.0   # extras are not part of the name\n" in text
        assert "PyJWT==2.14.0\n" in text and text.startswith("# Curatarr")
        assert dl.sync_pins(req, lock) == 0


def test_check_flags_pins_behind_the_lock_but_not_ahead():
    world = {"fastapi": ("fastapi", "0.141.1", []), "uvicorn": ("uvicorn", "0.53.0", []), "pyjwt": ("PyJWT", "2.14.0", [])}
    with tempfile.TemporaryDirectory() as d:
        req = pathlib.Path(d) / "requirements.txt"
        lock = pathlib.Path(d) / "lock" / "requirements.txt"
        lock.parent.mkdir()
        req.write_text(REQ, encoding="utf-8")
        lock.write_text("fastapi==0.142.0\nuvicorn==0.53.0\nPyJWT==2.13.0\n", encoding="utf-8")
        rep = dl.check(req, lock, requires=lambda n: world.get(dl.norm(n)))
    assert rep.pins_behind == [("fastapi", "0.141.1", "0.142.0")], "lock ahead → the pin follows"
    assert rep.below == [("fastapi", "0.141.1", "0.142.0")]
    assert rep.above == [("pyjwt", "2.14.0", "2.13.0")], "a pin ahead of the lock is a job for --compile, not a pin sync"


def test_apply_raises_follows_and_syncs_with_fakes():
    world = {"fastapi": ("fastapi", "0.141.1", ["starlette>=0.46"]), "starlette": ("starlette", "1.4.0", []),
             "uvicorn": ("uvicorn", "0.53.0", []), "pyjwt": ("PyJWT", "2.14.0", [])}
    runs = []

    def fake_run(cmd, **kw):
        runs.append(list(cmd))
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    def fetch(url):
        return {"urls": [{"digests": {"sha256": "1234"}}]}

    with tempfile.TemporaryDirectory() as d:
        req = pathlib.Path(d) / "requirements.txt"
        lock = pathlib.Path(d) / "lock" / "requirements.txt"
        lock.parent.mkdir()
        req.write_text(REQ, encoding="utf-8")
        lock.write_text("fastapi==0.142.0 \\\n    --hash=sha256:aaaa\nstarlette==1.3.1 \\\n    --hash=sha256:bbbb\n"
                        "uvicorn==0.53.0 \\\n    --hash=sha256:cccc\nPyJWT==2.14.0 \\\n    --hash=sha256:dddd\n",
                        encoding="utf-8")
        lines = []
        rep = dl.apply(req, lock, requires=lambda n: world.get(dl.norm(n)), run=fake_run, log=lines.append, fetch=fetch)
        assert runs and "--require-hashes" in runs[0], "the raise went through the hash check"
        written = dl.parse_lock(lock.read_text(encoding="utf-8"))
        assert written["fastapi"].version == "0.142.0", "fake pip did not really upgrade: the line stays"
        assert written["starlette"].version == "1.4.0" and written["starlette"].hashes == ["sha256:1234"], "lock followed"
        assert "fastapi==0.142.0" in req.read_text(encoding="utf-8"), "requirements.txt repeats the lock"
        assert any("raising 1 package" in l for l in lines) and any("requirements.txt: 1 pin" in l for l in lines)
        assert rep.pins_behind == [], "after the sync the pins agree with the lock"


def test_compile_uses_uv_universal_with_hashes_and_refuses_without_uv():
    cmds = []

    def fake_run(cmd, **kw):
        cmds.append(list(cmd))
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    with tempfile.TemporaryDirectory() as d:
        root = pathlib.Path(d)
        (root / "requirements.txt").write_text("fastapi==0.141.1\n", encoding="utf-8")
        (root / "lock").mkdir()
        (root / "lock" / "requirements-bandit.in").write_text("bandit[sarif]==1.9.4\n", encoding="utf-8")
        n = dl.compile_locks(run=fake_run, log=lambda s: None, uv=["uv"], root=root)
    assert n == 2, "the llm-scan input is missing here and is skipped, not invented"
    assert cmds[0][:3] == ["uv", "pip", "compile"] and "--universal" in cmds[0] and "--generate-hashes" in cmds[0]
    assert "--python-version" in cmds[0] and cmds[0][cmds[0].index("-o") + 1].endswith("requirements.txt")
    try:
        dl.compile_locks(run=fake_run, log=lambda s: None, uv=None if dl.uv_command() is None else ["nonexistent-uv"],
                         root=root)
    except RuntimeError as e:
        assert "uv" in str(e)
    else:
        assert dl.uv_command() is not None, "without uv the compile must refuse, not half-write"


def test_the_real_lock_is_consistent_with_requirements_and_the_inputs():
    text = dl.LOCK.read_text(encoding="utf-8")
    entries = dl.parse_lock(text)
    assert len(entries) > 40, f"{len(entries)} entries; the closure of 17 pins is far bigger"
    pins = dl.direct_pins(dl.REQUIREMENTS.read_text(encoding="utf-8"))
    pk = dl._packaging()
    assert pk is not None, "packaging must be importable wherever the battery runs"
    Version = pk[1]
    missing = [n for n in pins if n not in entries]
    assert not missing, f"direct pins absent from the lock (run --compile): {missing}"
    ahead = [(n, v, entries[n].version) for n, (v, _e) in pins.items() if Version(v) > Version(entries[n].version)]
    assert not ahead, f"requirements.txt ahead of the lock (bump the lock with --compile): {ahead}"
    if all(e.hashes for e in entries.values()):
        for e in entries.values():
            assert all(h.startswith("sha256:") for h in e.hashes), e.name
    home = pathlib.Path.home()
    for src, dst in dl.COMPILE_TARGETS:
        if src != "requirements.txt":
            inp = dl.ROOT / src
            assert inp.exists(), src
            assert dl.direct_pins(inp.read_text(encoding="utf-8")), f"{src} must pin its tool(s)"
        out = dl.ROOT / dst
        if out.exists():
            body = out.read_text(encoding="utf-8")
            for leak in (str(home), home.as_posix(), str(dl.ROOT), dl.ROOT.as_posix(), "C:\\Users", "/Users/"):
                assert leak not in body, f"{dst} carries a local path ({leak}); compile writes relative paths"


def test_compile_scrubs_a_local_path_uv_wrote():
    with tempfile.TemporaryDirectory() as d:
        root = pathlib.Path(d)
        f = root / "requirements.txt"
        f.write_text(f"# uv pip compile {root / 'requirements.txt'} -o out.txt\n"
                     f"pkg==1.0\n    # via -r {root.as_posix()}/requirements.txt\n", encoding="utf-8")
        assert dl._scrub_paths(f, root) == 2
        body = f.read_text(encoding="utf-8")
        assert str(root) not in body and root.as_posix() not in body
        assert "# via -r ./requirements.txt" in body


if __name__ == "__main__":
    fails = 0
    for name, fn in list(globals().items()):
        if name.startswith("test_") and callable(fn):
            try:
                fn()
                print(f"  PASS  {name}")
            except Exception as e:  # noqa: BLE001
                fails += 1
                print(f"  FAIL  {name}: {type(e).__name__}: {e}")
    sys.exit(1 if fails else 0)
