export const state = {
  taskEventSource: null,
  currentDelCategory: null,
  _delProposalsAll: null,
  _kbTab: null,
  discoverSections: null,
  currentRecsLane: null,
  currentRecsCategory: null,
  token: localStorage.getItem('curatarr_token') || '',
  currentUser: null,
  setupData: {},
  pendingDiscussContext: null,
  _lastPlayedEntries: null,
  _backlogState: null,
  pollInterval: null,
  taskStreamRetries: null,
  _recsPollTimer: null,
  _recsPollKillswitch: null,
  setupStep: 0,
  libraryCfg: [],
  _modal: null,
};
