"""The tested install, written down and hash-pinned: lock/requirements.txt.

requirements.txt pins the 17 packages Curatarr imports; everything they
pull in (~90 packages) was unpinned and invisible until 2026-09-22, when
the first real OSV scan showed the install running anyio 4.13.0 inside two
advisories. The lock is a *universal* pip requirements file — every package
of the closure with its version, an environment marker where a package is
platform-specific (uvloop on Linux, pywin32 on Windows) and the sha256 of
every distribution file — generated by ``uv pip compile --universal
--generate-hashes`` from requirements.txt (``--compile``). CI installs from
it with ``--require-hashes``; the launchers raise a package that fell below
it through the same hash check; scanners and Dependabot read it.

Rules, so the file can never lie or bite:

* The lock is the source of truth for versions. requirements.txt repeats
  the lock's versions for the direct pins (``--apply`` and ``--sync-pins``
  copy them over; requirements.txt never runs ahead of the lock — bump the
  lock with ``--compile`` for a deliberate change).
* The lock never lowers anything. A package installed below its lock line
  is raised (``pip install --require-hashes --no-deps`` from a temporary
  file holding exactly those lines); a package installed above it raises
  the lock line instead, with the hashes fetched from PyPI (offline: the
  line stays and the report says so).
* Entries whose marker rules them out on this platform are neither
  installed nor removed.
* A plain ``name==version`` line (no hashes) still works — that is what the
  lock looked like before uv — the raise then runs without the hash check.

    python -m src.deps_lock              report; exit 1 when anything differs
    python -m src.deps_lock --apply      raise below, follow above, sync the pins into requirements.txt
    python -m src.deps_lock --sync-pins  only the requirements.txt step
    python -m src.deps_lock --compile    regenerate every lock/*.txt from its input with uv

Marker evaluation and version ordering come from `packaging`, which is part
of the closure itself; when even that is missing (a venv before its first
pip run) the launchers skip the lock step and say so.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from importlib.metadata import PackageNotFoundError
from importlib.metadata import distribution as _distribution
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS = ROOT / "requirements.txt"
LOCK_DIR = ROOT / "lock"
LOCK = LOCK_DIR / "requirements.txt"
APPLY_CMD = "python -m src.deps_lock --apply"
PYTHON_TARGET = "3.12"          # the CI interpreter; uv resolves for it

# Every hashed lock and the input it is compiled from. The app lock's input
# is requirements.txt itself; the CI tools have one-line .in files.
COMPILE_TARGETS: List[Tuple[str, str]] = [
    ("requirements.txt", "lock/requirements.txt"),
    ("lock/requirements-bandit.in", "lock/requirements-bandit.txt"),
    ("lock/requirements-llm-scan.in", "lock/requirements-llm-scan.txt"),
]

_HEADER = """# The tested install, hash-pinned: every package the pins in ../requirements.txt
# pull in, with an environment marker where a package is platform-specific
# and the sha256 of every distribution file. Generated by
#     python -m src.deps_lock --compile        (uv pip compile --universal --generate-hashes)
# and kept current by the launchers (`--apply`: raise what fell below, follow
# what was raised by hand, never lower). CI installs it with --require-hashes;
# OSV-Scanner, the dependency graph and Dependabot read it. Edit requirements.txt
# for a deliberate change, then --compile; never edit this file by hand.
"""

_ENTRY = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)(\[[^\]]*\])?\s*==\s*([^\s;\\]+)"
                    r"\s*(?:;\s*(.*?))?\s*(\\)?\s*$")
_HASH = re.compile(r"^\s*--hash=(\S+)\s*(\\)?\s*$")
_PIN = re.compile(r"^(\s*)([A-Za-z0-9][A-Za-z0-9._-]*)(\s*\[[^\]]*\])?(\s*==\s*)([^\s;#]+)(.*)$")

RequiresFn = Callable[[str], Optional[Tuple[str, str, List[str]]]]


def norm(name: str) -> str:
    """PEP 503: case-insensitive, runs of -_. are one dash."""
    return re.sub(r"[-_.]+", "-", name).lower()


# ── the lock file ────────────────────────────────────────────────────────────

@dataclass
class Entry:
    name: str                        # spelling as written
    version: str
    marker: Optional[str] = None     # PEP 508 environment marker, without the leading ';'
    hashes: List[str] = field(default_factory=list)
    comments: List[str] = field(default_factory=list)   # "# via …" lines uv writes under an entry

    @property
    def key(self) -> str:
        return norm(self.name)

    def text(self) -> str:
        head = f"{self.name}=={self.version}"
        if self.marker:
            head += f" ; {self.marker}"
        if not self.hashes:
            return head + "\n" + "".join(c + "\n" for c in self.comments)
        lines = [head + " \\"]
        for i, h in enumerate(self.hashes):
            lines.append(f"    --hash={h}" + (" \\" if i < len(self.hashes) - 1 else ""))
        lines += self.comments
        return "\n".join(lines) + "\n"


def parse_lock(text: str) -> Dict[str, Entry]:
    """{normalised name: Entry} from a uv-style or plain requirements file.
    Continuation lines, markers, hashes and the '# via' comments are kept;
    anything that is not a pin (options, -r lines) is skipped."""
    entries: Dict[str, Entry] = {}
    cur: Optional[Entry] = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip():
            cur = None
            continue
        if line.lstrip().startswith("#"):
            if cur is not None and line.startswith((" ", "\t")):
                cur.comments.append(line)
            continue
        m = _HASH.match(line)
        if m and cur is not None:
            cur.hashes.append(m.group(1))
            continue
        m = _ENTRY.match(line)
        if m:
            cur = Entry(name=m.group(1), version=m.group(3), marker=(m.group(4) or "").strip() or None)
            entries[cur.key] = cur
            continue
        cur = None                      # an option line or something else: not ours
    return entries


def format_lock(entries: Dict[str, Entry], header: str = _HEADER) -> str:
    return header + "".join(entries[k].text() for k in sorted(entries))


def lock_header(text: str) -> str:
    """The comment block before the first entry, so a rewrite keeps uv's
    'autogenerated by' note (or ours)."""
    out = []
    for line in text.splitlines():
        if line.startswith("#") or not line.strip():
            out.append(line)
        else:
            break
    head = "\n".join(out).rstrip("\n")
    return (head + "\n") if head else _HEADER


def direct_pins(text: str) -> Dict[str, Tuple[str, List[str]]]:
    """{normalised name: (version, [extras])} from requirements.txt."""
    out: Dict[str, Tuple[str, List[str]]] = {}
    for line in text.splitlines():
        m = _PIN.match(line.split("#", 1)[0])
        if m:
            extras = [e.strip() for e in (m.group(3) or "").strip(" []").split(",") if e.strip()]
            out[norm(m.group(2))] = (m.group(5), extras)
    return out


# ── the closure of the direct pins on THIS interpreter ───────────────────────

def _packaging():
    """packaging from the environment, else pip's vendored copy, else None."""
    try:
        from packaging.markers import Marker
        from packaging.requirements import Requirement
        from packaging.version import Version
        return Requirement, Version, Marker
    except ImportError:
        try:
            from pip._vendor.packaging.markers import Marker  # type: ignore
            from pip._vendor.packaging.requirements import Requirement  # type: ignore
            from pip._vendor.packaging.version import Version  # type: ignore
            return Requirement, Version, Marker
        except ImportError:
            return None


def _dist_requires(name: str) -> Optional[Tuple[str, str, List[str]]]:
    """(canonical spelling, installed version, requirement strings) or None."""
    try:
        d = _distribution(name)
    except PackageNotFoundError:
        return None
    return (d.metadata["Name"] or name), d.version, list(d.requires or [])


def closure(roots: Dict[str, Tuple[str, List[str]]],
            requires: RequiresFn = _dist_requires,
            packaging=None) -> Tuple[Dict[str, str], Dict[str, str], List[str]]:
    """Walk installed metadata from the roots, honouring extras and
    environment markers for THIS interpreter. Returns ({norm: version},
    {norm: spelling}, [roots that are not installed])."""
    pk = packaging or _packaging()
    if pk is None:
        raise RuntimeError("packaging is not importable; run pip for requirements.txt first")
    Requirement = pk[0]
    versions: Dict[str, str] = {}
    spelling: Dict[str, str] = {}
    missing: List[str] = []
    seen_extras: Dict[str, set] = {}
    queue: List[Tuple[str, Tuple[str, ...]]] = [(n, tuple(sorted(ex))) for n, (_v, ex) in roots.items()]
    while queue:
        name, extras = queue.pop()
        key = norm(name)
        first = key not in versions
        new_extras = set(extras) - seen_extras.get(key, set())
        if not first and not new_extras:
            continue
        info = requires(name)
        if info is None:
            if first and name not in missing:
                missing.append(name)
            continue
        spelled, ver, reqs = info
        versions[key] = ver
        spelling[key] = spelled
        wanted = set(new_extras) | ({""} if first else set())
        seen_extras.setdefault(key, set()).update(extras)
        for r in reqs:
            try:
                req = Requirement(r)
            except Exception:  # noqa: BLE001
                continue
            if req.marker is None:
                if "" in wanted:
                    queue.append((req.name, tuple(sorted(req.extras))))
                continue
            if any(req.marker.evaluate({"extra": extra}) for extra in wanted):
                queue.append((req.name, tuple(sorted(req.extras))))
    return versions, spelling, missing


def _applies_here(entry: Entry, packaging=None) -> bool:
    """True when the entry's marker holds on this interpreter (no marker = yes)."""
    if not entry.marker:
        return True
    pk = packaging or _packaging()
    if pk is None:
        return True
    try:
        return bool(pk[2](entry.marker).evaluate())
    except Exception:  # noqa: BLE001
        return True


# ── comparison ───────────────────────────────────────────────────────────────

@dataclass
class LockReport:
    lock: Dict[str, Entry] = field(default_factory=dict)
    installed: Dict[str, str] = field(default_factory=dict)
    spelling: Dict[str, str] = field(default_factory=dict)
    below: List[Tuple[str, str, str]] = field(default_factory=list)   # (key, installed, locked): raise
    above: List[Tuple[str, str, str]] = field(default_factory=list)   # (key, installed, locked): lock follows
    unlocked: List[str] = field(default_factory=list)                 # in the closure, not in the lock
    unused: List[str] = field(default_factory=list)                   # in the lock, applies here, not installed
    foreign: List[str] = field(default_factory=list)                  # in the lock, ruled out by its marker here
    pins_behind: List[Tuple[str, str, str]] = field(default_factory=list)  # (key, requirements, lock): sync
    hashed: bool = False
    missing_roots: List[str] = field(default_factory=list)
    error: Optional[str] = None

    @property
    def clean(self) -> bool:
        return not (self.below or self.above or self.unlocked or self.pins_behind or self.error)

    def lines(self) -> List[str]:
        out = [f"{n}: installed {i}, lock says {l} (will be raised)" for n, i, l in self.below]
        out += [f"{n}: installed {i}, lock says {l} (lock follows)" for n, i, l in self.above]
        out += [f"{n}: installed, not in the lock" for n in self.unlocked]
        out += [f"{n}: requirements.txt says {r}, lock says {l} (pin follows the lock)" for n, r, l in self.pins_behind]
        return out

    def summary(self) -> str:
        if self.error:
            return f"lock not checked: {self.error}"
        if self.clean:
            return (f"lock matches this interpreter ({len(self.lock)} packages, "
                    f"{'hash-pinned' if self.hashed else 'no hashes yet'})")
        shown = self.lines()
        return (f"lock differs: {len(self.below)} below, {len(self.above)} above, "
                f"{len(self.unlocked)} unlocked, {len(self.pins_behind)} pins behind: "
                + "; ".join(shown[:8]) + (" …" if len(shown) > 8 else "") + f". Run: {APPLY_CMD}")

    def as_dict(self) -> dict:
        return {
            "clean": self.clean,
            "packages": len(self.lock),
            "hashed": self.hashed,
            "below": [{"name": n, "installed": i, "locked": l} for n, i, l in self.below],
            "above": [{"name": n, "installed": i, "locked": l} for n, i, l in self.above],
            "unlocked": list(self.unlocked),
            "unused": list(self.unused),
            "pins_behind": [{"name": n, "requirements": r, "locked": l} for n, r, l in self.pins_behind],
            "error": self.error,
            "command": APPLY_CMD,
        }


def _lower(Version, a: str, b: str) -> bool:
    if Version is None:
        return a != b
    try:
        return Version(a) < Version(b)
    except Exception:  # noqa: BLE001
        return a != b


def compare(lock_text: str, installed: Dict[str, str], packaging=None) -> LockReport:
    pk = packaging or _packaging()
    Version = pk[1] if pk else None
    rep = LockReport(lock=parse_lock(lock_text), installed=dict(installed))
    rep.hashed = bool(rep.lock) and all(e.hashes for e in rep.lock.values())
    for key, ver in sorted(installed.items()):
        e = rep.lock.get(key)
        if e is None:
            rep.unlocked.append(key)
        elif _lower(Version, ver, e.version):
            rep.below.append((key, ver, e.version))
        elif _lower(Version, e.version, ver):
            rep.above.append((key, ver, e.version))
    for key, e in sorted(rep.lock.items()):
        if key in installed:
            continue
        (rep.unused if _applies_here(e, pk) else rep.foreign).append(key)
    return rep


def check(requirements: Path = REQUIREMENTS, lock: Path = LOCK,
          requires: RequiresFn = _dist_requires) -> LockReport:
    """The report the server logs and Settings → Maintenance shows."""
    req_text = Path(requirements).read_text(encoding="utf-8")
    pins = direct_pins(req_text)
    try:
        versions, spelling, missing_roots = closure(pins, requires)
    except Exception as e:  # noqa: BLE001
        return LockReport(error=f"{type(e).__name__}: {e}")
    lock_path = Path(lock)
    lock_text = lock_path.read_text(encoding="utf-8") if lock_path.exists() else ""
    rep = compare(lock_text, versions)
    rep.spelling = spelling
    rep.missing_roots = missing_roots
    pk = _packaging()
    Version = pk[1] if pk else None
    for key, (ver, _ex) in pins.items():
        e = rep.lock.get(key)
        if e is not None and e.version != ver and not _lower(Version, e.version, ver):
            rep.pins_behind.append((key, ver, e.version))
    if not lock_text:
        rep.error = f"{lock_path.name} is missing"
    return rep


# ── PyPI hashes for a version the lock did not know ──────────────────────────

def pypi_hashes(name: str, version: str, fetch=None) -> List[str]:
    """sha256 of every distribution file of one release, 'sha256:…' each;
    [] when PyPI cannot be reached or the release is unknown.

    httpx, imported here rather than urllib: this runs from ``--apply`` after
    the first pip run, when httpx exists, and Bandit's B310 has no reason to
    look at an ``urlopen`` (the GPU probe went the same way)."""
    def _default(url: str) -> dict:
        import httpx
        r = httpx.get(url, headers={"User-Agent": "curatarr-deps-lock"}, timeout=30, follow_redirects=True)
        r.raise_for_status()
        return r.json()
    try:
        data = (fetch or _default)(f"https://pypi.org/pypi/{name}/{version}/json")
    except Exception:  # noqa: BLE001
        return []
    out = []
    for f in data.get("urls") or []:
        if f.get("yanked"):
            continue
        sha = (f.get("digests") or {}).get("sha256")
        if sha:
            out.append(f"sha256:{sha}")
    return sorted(set(out))


# ── writing, raising, syncing ────────────────────────────────────────────────

def merged(rep: LockReport, spelling: Dict[str, str], fetch=None, log=print) -> Dict[str, Entry]:
    """What the lock should say after this machine: below → the lock line
    stays (the raise is retried); above → the line follows the install with
    fresh hashes when PyPI answers; unlocked → added when PyPI answers."""
    out = {k: e for k, e in rep.lock.items()}
    for key, installed, _locked in rep.above:
        e = out[key]
        hashes = pypi_hashes(e.name, installed, fetch) if e.hashes else []
        if e.hashes and not hashes:
            log(f"[lock] {e.name} {installed} installed above the lock; PyPI unreachable, line kept at {e.version}")
            continue
        out[key] = Entry(name=e.name, version=installed, marker=e.marker, hashes=hashes,
                         comments=[c for c in e.comments if "via" in c])
    for key in rep.unlocked:
        name = spelling.get(key, key)
        hashes = pypi_hashes(name, rep.installed[key], fetch) if rep.hashed else []
        if rep.hashed and not hashes:
            log(f"[lock] {name} {rep.installed[key]} is installed but not locked; PyPI unreachable, not added")
            continue
        out[key] = Entry(name=name, version=rep.installed[key], hashes=hashes)
    return out


def raise_below(rep: LockReport, run=subprocess.run, log=print) -> List[str]:
    """pip install for every package below its lock line, from a temporary
    requirements file that carries exactly those lines — with --require-hashes
    when the lock has hashes. One call for all; on failure one call per
    package so a single conflict does not block the rest. Returns the keys
    that failed."""
    if not rep.below:
        return []
    def _install(keys: List[str]) -> bool:
        lines = []
        for key in keys:
            e = rep.lock[key]
            lines.append(Entry(name=e.name, version=e.version, hashes=list(e.hashes)).text())
        fd, path = tempfile.mkstemp(prefix="curatarr-lock-", suffix=".txt")
        try:
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
                fh.write("".join(lines))
            cmd = [sys.executable, "-m", "pip", "install", "--no-deps", "-r", path,
                   "--quiet", "--disable-pip-version-check"]
            if rep.hashed:
                cmd.insert(4, "--require-hashes")
            r = run(cmd, capture_output=True, text=True)
            if r.returncode != 0:
                sys.stderr.write((r.stderr or r.stdout or "")[-800:])
                return False
            return True
        finally:
            try:
                os.unlink(path)
            except OSError:
                pass
    keys = [k for k, _i, _l in rep.below]
    if _install(keys):
        failed: List[str] = []
    else:
        failed = [k for k in keys if not _install([k])]
    if len(failed) < len(keys):
        import importlib
        importlib.invalidate_caches()
    return failed


def write_lock(entries: Dict[str, Entry], lock: Path = LOCK, header: Optional[str] = None) -> bool:
    """Write only when the content changes; returns True when it did."""
    lock = Path(lock)
    old = lock.read_text(encoding="utf-8") if lock.exists() else ""
    text = format_lock(entries, header or (lock_header(old) if old else _HEADER))
    if old == text:
        return False
    lock.parent.mkdir(parents=True, exist_ok=True)
    lock.write_text(text, encoding="utf-8", newline="\n")
    return True


def sync_pins(requirements: Path = REQUIREMENTS, lock: Path = LOCK) -> int:
    """requirements.txt repeats the lock's version for every direct pin —
    the line keeps its extras, spacing and comment. Returns the number of
    lines changed. The lock is the truth; a pin the lock does not know is
    left alone (run --compile)."""
    lock_entries = parse_lock(Path(lock).read_text(encoding="utf-8")) if Path(lock).exists() else {}
    if not lock_entries:
        return 0
    req = Path(requirements)
    raw = req.read_text(encoding="utf-8")
    eol = "\r\n" if "\r\n" in raw else "\n"
    changed = 0
    out = []
    for line in raw.replace("\r\n", "\n").split("\n"):
        m = _PIN.match(line.split("#", 1)[0])
        if m:
            e = lock_entries.get(norm(m.group(2)))
            if e is not None and e.version != m.group(5):
                line = m.group(1) + m.group(2) + (m.group(3) or "") + m.group(4) + e.version + m.group(6) \
                    + ("#" + line.split("#", 1)[1] if "#" in line else "")
                changed += 1
        out.append(line)
    if changed:
        req.write_text("\n".join(out).replace("\n", eol), encoding="utf-8", newline="")
    return changed


def apply(requirements: Path = REQUIREMENTS, lock: Path = LOCK,
          requires: RequiresFn = _dist_requires, run=subprocess.run, log=print, fetch=None) -> LockReport:
    """The launchers' step: raise what is below, let the lock follow what is
    above, then repeat the lock's versions in requirements.txt."""
    rep = check(requirements, lock, requires)
    if rep.error and not rep.installed:          # nothing walkable: no packaging, no closure
        log(f"[lock] {rep.summary()}")
        return rep
    if rep.below:
        log(f"[lock] raising {len(rep.below)} package(s) to the lock: "
            + ", ".join(f"{n} {i}->{l}" for n, i, l in rep.below))
        failed = raise_below(rep, run, log)
        if failed:
            log(f"[lock] pip failed for: {', '.join(failed)} (kept in the lock, retried next start)")
        rep = check(requirements, lock, requires)
    if rep.lock:
        entries = merged(rep, rep.spelling, fetch, log)
        if write_lock(entries, lock):
            log(f"[lock] refreshed {Path(lock).name}: {len(entries)} packages")
    n = sync_pins(requirements, lock)
    if n:
        log(f"[lock] requirements.txt: {n} pin line(s) now repeat the lock")
    rep = check(requirements, lock, requires)
    log(f"[lock] {rep.summary()}")
    return rep


# ── compile with uv ──────────────────────────────────────────────────────────

def uv_command() -> Optional[List[str]]:
    """How to run uv here: the module of this interpreter, else the binary."""
    try:
        r = subprocess.run([sys.executable, "-m", "uv", "--version"], capture_output=True, text=True, timeout=30)
        if r.returncode == 0:
            return [sys.executable, "-m", "uv"]
    except Exception:  # noqa: BLE001
        pass
    exe = shutil.which("uv")
    return [exe] if exe else None


def compile_locks(targets=COMPILE_TARGETS, run=subprocess.run, log=print, uv: Optional[List[str]] = None,
                  root: Path = ROOT, keep_versions: bool = False) -> int:
    """uv pip compile --universal --generate-hashes for every target whose
    input exists. Returns the number of locks written; raises when uv is not
    available, because a half-done lock set is worse than none.

    keep_versions: hand the versions the lock ALREADY holds to uv as
    constraints, so a compile adds hashes and markers without moving a single
    version — the first compile of a tested install, or a re-compile after
    editing an input. Without it uv resolves the newest versions the pins
    allow, and every machine raises to them at its next start."""
    uv = uv or uv_command()
    if not uv:
        raise RuntimeError("uv is not installed for this interpreter: pip install uv")
    written = 0
    for src, dst in targets:
        src_p, dst_p = root / src, root / dst
        if not src_p.exists():
            log(f"[lock] {src}: no such input, skipped")
            continue
        # Relative paths, cwd=root: uv writes the command line and the
        # "# via -r <input>" provenance into the file, and an absolute path
        # would carry the user's home directory into a public repository
        # (the first compile did: 93 lines with C:\Users\<name>\…).
        cmd = uv + ["pip", "compile", src, "--universal", "--generate-hashes",
                    "--python-version", PYTHON_TARGET, "--quiet", "-o", dst]
        constraints = None
        if keep_versions and dst_p.exists():
            current = parse_lock(dst_p.read_text(encoding="utf-8"))
            if current:
                constraints = f"{Path(dst).parent.as_posix()}/.keep-versions.txt"
                (root / constraints).write_text(
                    "".join(f"{e.name}=={e.version}" + (f" ; {e.marker}" if e.marker else "") + "\n"
                            for e in current.values()),
                    encoding="utf-8", newline="\n")
                cmd += ["-c", constraints]
        try:
            r = run(cmd, capture_output=True, text=True, cwd=str(root))
        finally:
            if constraints:
                try:
                    os.unlink(root / constraints)
                except OSError:
                    pass
        if r.returncode != 0:
            raise RuntimeError(f"uv failed for {src}: {(r.stderr or r.stdout or '')[-600:]}")
        if dst_p.exists():
            leaked = _scrub_paths(dst_p, root)
            if leaked:
                log(f"[lock] {dst}: {leaked} line(s) carried a local path, rewritten relative")
        log(f"[lock] compiled {dst} from {src}" + (" (versions kept)" if constraints else ""))
        written += 1
    return written


def _scrub_paths(path: Path, root: Path) -> int:
    """Replace the repo root and the home directory in a compiled lock with
    relative spellings; returns the number of lines touched. Belt and braces
    behind the relative-path invocation."""
    text = path.read_text(encoding="utf-8")
    out, touched = [], 0
    for line in text.splitlines():
        new = line
        for absolute, rel in ((str(root), "."), (root.as_posix(), "."),
                              (str(Path.home()), "~"), (Path.home().as_posix(), "~")):
            if absolute and absolute in new:
                new = new.replace(absolute + "\\", rel + "/").replace(absolute + "/", rel + "/").replace(absolute, rel)
        if new != line:
            touched += 1
        out.append(new)
    if touched:
        path.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    return touched


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="the tested install vs. this interpreter")
    ap.add_argument("--apply", action="store_true", help="raise below, follow above, sync the pins")
    ap.add_argument("--sync-pins", action="store_true", help="repeat the lock's versions in requirements.txt")
    ap.add_argument("--compile", action="store_true", help="regenerate every lock/*.txt with uv")
    ap.add_argument("--keep-versions", action="store_true",
                    help="with --compile: constrain uv to the versions the lock already holds (hashes and markers only)")
    ap.add_argument("--requirements", default=str(REQUIREMENTS))
    ap.add_argument("--lock", default=str(LOCK))
    args = ap.parse_args(argv)
    req, lock = Path(args.requirements), Path(args.lock)
    if args.compile:
        try:
            n = compile_locks(keep_versions=args.keep_versions)
        except RuntimeError as e:
            print(f"[lock] {e}")
            return 1
        print(f"[lock] {n} lock file(s) compiled; now: python -m src.deps_lock --sync-pins")
        return 0
    if args.sync_pins:
        n = sync_pins(req, lock)
        print(f"[lock] {n} pin line(s) in {req.name} now repeat the lock")
        return 0
    if args.apply:
        # start.bat only shows these lines on the console; a start nobody
        # watched left "why was starlette not raised?" unanswerable
        # (2026-09-23). Write them to the app log as well when it exists.
        import logging
        try:
            from src.log_setup import init_logging
            init_logging("INFO")
        except Exception:  # noqa: BLE001 — logging is a nicety here, not a requirement
            pass
        file_log = logging.getLogger("curatarr.deps_lock")

        def both(msg: str) -> None:
            print(msg)
            file_log.info(msg)
        return 0 if apply(req, lock, log=both).clean else 1
    rep = check(req, lock)
    print(f"[lock] {rep.summary()}")
    return 0 if rep.clean else 1


if __name__ == "__main__":
    sys.exit(main())
